version: '3'

services:
  php:
    container_name: php_exercise
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
    ports: 
      - 80:80
  mysql:
    container_name: mysql_exercise
    build:
      context: ./
      dockerfile: Dockerfile_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=exercise_one
      - MYSQL_PASSWORD=root
      - MYSQL_DB=exercise_one
    ports: 
      - 3306:3306
